---
# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

default:
  # All jobs are interruptible by default
  interruptible: true

stages:
  - sync
  - lint
  - test
  # - coverage
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  POETRY_VERSION: 1.3.2
  PRECOMMIT_USE_POETRY: "true"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit

# Conditions
#############
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'

# Workflow
###########
workflow:
  rules:
    - <<: *if-tag
    - <<: *if-default-branch-refs
    - <<: *if-merge-request

include:
  - project: 'labs/salt-automation'
    file:
      - gitlab-ci-templates/common/no-interrupt.v1.yml
      - gitlab-ci-templates/common/conventional-commits.v1.yml
      - gitlab-ci-templates/common/pre-commit.v1.yml
      - gitlab-ci-templates/common/rules.v1.yml
      - gitlab-ci-templates/python/pypi-cc.v1.yml
      - gitlab-ci-templates/python/pytest-meta.v1.yml

Check Docs:
  image: python:3.10
  stage: lint
  script:
    - pip install pyyaml more-itertools
    - python tools/check_docs.py

.pytest_extras:
  extends: .pytest
  variables:
    HYPOTHESIS_PROFILE: "ci"
  before_script:
    - !reference [.pytest, before_script]
    - $POETRY_HOME/bin/poetry install -vv --extras all

Test on Python 3.8:
  extends: .pytest_extras
  image: python:3.8

Test on Python 3.9:
  extends: .pytest_extras
  image: python:3.9

Test on Python 3.10:
  extends: .pytest_extras
  image: python:3.10

# Test on Python 3.11:
#   extends: .pytest_extras
#   image: python:3.11

pages:
  image: python:3.8
  stage: release
  needs: []
  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install -vv --extras all
  script:
    - poetry run mkdocs build --strict --site-dir public
  artifacts:
    paths:
      - public
